config/routes.rb
SimpleFormDemoApp::Application.routes.draw do

  resources :doohickeys, except: [:edit, :update]
  root to: 'doohickeys#index'

end

app/models/doohickey.rb
class Doohickey < ActiveRecord::Base

  validates_presence_of :name
  validate :unique_name_validation

  attr_accessible :name

  def unique_name_validation
    other_doohickey = Doohickey.find_by_name(name)
    if other_doohickey
      errors.add(
        :name,
        "This name is already taken by <a href='/doohickey/#{other_doohickey.id}'>#{other_doohickey.name}</a>"
      )
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/doohickeys_controller.rb
class DoohickeysController < ApplicationController

  def index
    @doohickeys = Doohickey.order(:name).all
  end

  def new
    @doohickey = Doohickey.new
  end

  def create
    @doohickey = Doohickey.new(params[:doohickey])
    if @doohickey.save
      redirect_to doohickeys_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doohickeys/index.html.erb
<h1>DOOHICKEYS!</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @doohickeys.each do |doohickey| %>
      <tr>
        <td><%= doohickey.id %></td>
        <td><%= doohickey.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/doohickeys/new.html.erb
<h1>New DOOHICKEY!</h1>

<%= simple_form_for @doohickey do |form| %>
  <%= form.input :name %>
  <%= form.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleFormDemoApp</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <ul class="menu">
      <li><%= link_to 'Home', doohickeys_path %></li>
      <li><%= link_to 'New Doohickey', new_doohickey_path %></li>
    </ul>

    <%= yield %>

  </body>
</html>